{% set name = "edgetest-conda" %}
{% set version = "2024.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7357d5a77ebdba377c013de2c0a2a264ae413a923218b6683eb58c39ef1ab073

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv --no-deps .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - edgetest >=2021.12.3
    - conda
    - python >=3.8

test:
  imports:
    - edgetest_conda.plugin

about:
  home: https://github.com/capitalone/edgetest-conda
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: edgetest-conda is a conda plugin for edgetest
  description: |
    This plugin allows users to create virtual environments using conda instead of venv when using edgetest
  doc_url: https://capitalone.github.io/edgetest-conda
  dev_url: https://github.com/capitalone/edgetest-conda

extra:
  recipe-maintainers:
    - gladysteh99
    - jdawang
    - NikhilJArora
    - fdosani
    - ak-gupta
